"""Esquema inicial de la plataforma SAMM.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-24 15:30:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_roles_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_public_id'), ['public_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('email_normalized', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email_active', ['email_normalized', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email_normalized'), ['email_normalized'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)

    op.create_table('answer_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_answer_sets_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_answer_sets_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_sets')),
    sa.UniqueConstraint('external_code', name=op.f('uq_answer_sets_external_code'))
    )
    with op.batch_alter_table('answer_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_sets_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_sets_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_sets_public_id'), ['public_id'], unique=True)

    op.create_table('application_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_application_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_settings'))
    )
    with op.batch_alter_table('application_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_settings_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_settings_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_application_settings_public_id'), ['public_id'], unique=True)

    op.create_table('business_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_business_functions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_business_functions_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_functions'))
    )
    with op.batch_alter_table('business_functions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_functions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_business_functions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_functions_public_id'), ['public_id'], unique=True)

    op.create_table('maturity_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_maturity_levels_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_maturity_levels_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maturity_levels')),
    sa.UniqueConstraint('level_number', name=op.f('uq_maturity_levels_level_number'))
    )
    with op.batch_alter_table('maturity_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maturity_levels_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_maturity_levels_public_id'), ['public_id'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('unread', 'read', 'archived', name='notification_status', native_enum=False), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('legal_name', sa.String(length=240), nullable=True),
    sa.Column('tax_identifier', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_organizations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_organizations_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_tax_identifier'), ['tax_identifier'], unique=False)

    op.create_table('questionnaire_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('version_number', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='questionnaire_status', native_enum=False), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_file_hash', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_questionnaire_versions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], name=op.f('fk_questionnaire_versions_published_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_questionnaire_versions_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questionnaire_versions')),
    sa.UniqueConstraint('version_number', name=op.f('uq_questionnaire_versions_version_number'))
    )
    with op.batch_alter_table('questionnaire_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionnaire_versions_public_id'), ['public_id'], unique=True)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_code', sa.String(length=100), nullable=False),
    sa.Column('canonical_name', sa.String(length=240), nullable=True),
    sa.Column('current_revision_number', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_questions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_questions_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_external_code'), ['external_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_questions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_public_id'), ['public_id'], unique=True)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_user_roles_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_table('answer_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_set_id', sa.Integer(), nullable=False),
    sa.Column('option_code', sa.String(length=80), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['answer_set_id'], ['answer_sets.id'], name=op.f('fk_answer_options_answer_set_id_answer_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_answer_options_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_answer_options_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_options')),
    sa.UniqueConstraint('answer_set_id', 'option_code', name='uq_answer_options_set_code')
    )
    with op.batch_alter_table('answer_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_options_answer_set_id'), ['answer_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_options_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_options_public_id'), ['public_id'], unique=True)

    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'configured', 'in_progress', 'in_review', 'observed', 'completed', 'published', 'closed', 'cancelled', name='assessment_status', native_enum=False), nullable=False),
    sa.Column('target_maturity_level', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('scoring_source', sa.Enum('declared', 'reviewed', 'approved', name='assessment_scoring_source', native_enum=False), nullable=False),
    sa.Column('results_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings_snapshot', sa.JSON(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_assessments_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assessments_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['questionnaire_version_id'], ['questionnaire_versions.id'], name=op.f('fk_assessments_questionnaire_version_id_questionnaire_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_assessments_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_assessments_questionnaire_version_id'), ['questionnaire_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_target_date'), ['target_date'], unique=False)

    op.create_table('organization_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('membership_role', sa.String(length=40), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='membership_status', native_enum=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_memberships_org_user')
    )
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_memberships_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_organization_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('security_practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_function_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_function_id'], ['business_functions.id'], name=op.f('fk_security_practices_business_function_id_business_functions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_security_practices_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_security_practices_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_practices')),
    sa.UniqueConstraint('business_function_id', 'code', name='uq_security_practices_function_code')
    )
    with op.batch_alter_table('security_practices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_practices_business_function_id'), ['business_function_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_practices_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_practices_public_id'), ['public_id'], unique=True)

    op.create_table('assessment_score_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_number', sa.Integer(), nullable=False),
    sa.Column('scoring_source', sa.Enum('declared', 'reviewed', 'approved', name='score_snapshot_source', native_enum=False), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculated_by_id', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('progress_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('calculation_version', sa.String(length=40), nullable=False),
    sa.Column('is_published_snapshot', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_score_snapshots_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['calculated_by_id'], ['users.id'], name=op.f('fk_assessment_score_snapshots_calculated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_score_snapshots')),
    sa.UniqueConstraint('assessment_id', 'snapshot_number', name='uq_score_snapshot_number')
    )
    with op.batch_alter_table('assessment_score_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_score_snapshots_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_score_snapshots_public_id'), ['public_id'], unique=True)

    op.create_table('assessment_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_role', sa.Enum('respondent', 'reviewer', name='assignment_role', native_enum=False), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_users_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_assessment_users_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assessment_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_users')),
    sa.UniqueConstraint('assessment_id', 'user_id', 'assignment_role', name='uq_assessment_users_assignment')
    )
    with op.batch_alter_table('assessment_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_users_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_users_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_assessment_users_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_public_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_audit_logs_assessment_id_assessments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_public_id'), ['entity_public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_public_id'), ['public_id'], unique=True)

    op.create_table('practice_streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_practice_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_practice_streams_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['security_practice_id'], ['security_practices.id'], name=op.f('fk_practice_streams_security_practice_id_security_practices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_practice_streams_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_streams')),
    sa.UniqueConstraint('security_practice_id', 'code', name='uq_practice_streams_practice_code')
    )
    with op.batch_alter_table('practice_streams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_streams_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_streams_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_practice_streams_security_practice_id'), ['security_practice_id'], unique=False)

    op.create_table('assessment_score_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('dimension_type', sa.String(length=40), nullable=False),
    sa.Column('dimension_key', sa.String(length=160), nullable=False),
    sa.Column('dimension_name', sa.String(length=240), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('normalized_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('target_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gap', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('applicable_count', sa.Integer(), nullable=False),
    sa.Column('not_applicable_count', sa.Integer(), nullable=False),
    sa.Column('pending_count', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['score_snapshot_id'], ['assessment_score_snapshots.id'], name=op.f('fk_assessment_score_items_score_snapshot_id_assessment_score_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_score_items'))
    )
    with op.batch_alter_table('assessment_score_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_score_items_dimension_type'), ['dimension_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_score_items_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_assessment_score_items_score_snapshot_id'), ['score_snapshot_id'], unique=False)

    op.create_table('question_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('business_function_id', sa.Integer(), nullable=False),
    sa.Column('security_practice_id', sa.Integer(), nullable=False),
    sa.Column('practice_stream_id', sa.Integer(), nullable=False),
    sa.Column('maturity_level_id', sa.Integer(), nullable=False),
    sa.Column('answer_set_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('guidance_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('supersedes_revision_id', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='question_revision_status', native_enum=False), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_set_id'], ['answer_sets.id'], name=op.f('fk_question_revisions_answer_set_id_answer_sets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_function_id'], ['business_functions.id'], name=op.f('fk_question_revisions_business_function_id_business_functions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_question_revisions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maturity_level_id'], ['maturity_levels.id'], name=op.f('fk_question_revisions_maturity_level_id_maturity_levels'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['practice_stream_id'], ['practice_streams.id'], name=op.f('fk_question_revisions_practice_stream_id_practice_streams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_revisions_question_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_practice_id'], ['security_practices.id'], name=op.f('fk_question_revisions_security_practice_id_security_practices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_revision_id'], ['question_revisions.id'], name=op.f('fk_question_revisions_supersedes_revision_id_question_revisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_question_revisions_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_revisions')),
    sa.UniqueConstraint('question_id', 'revision_number', name='uq_question_revisions_question_number')
    )
    with op.batch_alter_table('question_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_revisions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_revisions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_question_revisions_question_id'), ['question_id'], unique=False)

    op.create_table('assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('source_question_revision_id', sa.Integer(), nullable=False),
    sa.Column('external_code_snapshot', sa.String(length=100), nullable=False),
    sa.Column('question_text_snapshot', sa.Text(), nullable=False),
    sa.Column('guidance_snapshot', sa.Text(), nullable=True),
    sa.Column('criteria_snapshot', sa.JSON(), nullable=False),
    sa.Column('answer_options_snapshot', sa.JSON(), nullable=False),
    sa.Column('business_function_snapshot', sa.JSON(), nullable=False),
    sa.Column('security_practice_snapshot', sa.JSON(), nullable=False),
    sa.Column('practice_stream_snapshot', sa.JSON(), nullable=False),
    sa.Column('maturity_level_snapshot', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('current_status', sa.Enum('unanswered', 'draft', 'answered', 'submitted', 'observed', 'rejected', 'approved', name='assessment_question_status', native_enum=False), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_questions_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_question_revision_id'], ['question_revisions.id'], name=op.f('fk_assessment_questions_source_question_revision_id_question_revisions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_questions')),
    sa.UniqueConstraint('assessment_id', 'source_question_revision_id', name='uq_assessment_question_source')
    )
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_questions_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_questions_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_questions_external_code_snapshot'), ['external_code_snapshot'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_questions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_assessment_questions_source_question_revision_id'), ['source_question_revision_id'], unique=False)

    op.create_table('question_quality_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_revision_id', sa.Integer(), nullable=False),
    sa.Column('criterion_text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_question_quality_criteria_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_revision_id'], ['question_revisions.id'], name=op.f('fk_question_quality_criteria_question_revision_id_question_revisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_question_quality_criteria_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_quality_criteria'))
    )
    with op.batch_alter_table('question_quality_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_quality_criteria_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_question_quality_criteria_question_revision_id'), ['question_revision_id'], unique=False)

    op.create_table('questionnaire_version_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionnaire_version_id', sa.Integer(), nullable=False),
    sa.Column('question_revision_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('weight_override', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_revision_id'], ['question_revisions.id'], name=op.f('fk_questionnaire_version_questions_question_revision_id_question_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['questionnaire_version_id'], ['questionnaire_versions.id'], name=op.f('fk_questionnaire_version_questions_questionnaire_version_id_questionnaire_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questionnaire_version_questions')),
    sa.UniqueConstraint('questionnaire_version_id', 'question_revision_id', name='uq_questionnaire_version_revision')
    )
    with op.batch_alter_table('questionnaire_version_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionnaire_version_questions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_questionnaire_version_questions_question_revision_id'), ['question_revision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaire_version_questions_questionnaire_version_id'), ['questionnaire_version_id'], unique=False)

    op.create_table('assessment_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_question_id', sa.Integer(), nullable=False),
    sa.Column('respondent_id', sa.Integer(), nullable=True),
    sa.Column('selected_option_code', sa.String(length=80), nullable=True),
    sa.Column('selected_option_text_snapshot', sa.Text(), nullable=True),
    sa.Column('selected_weight_snapshot', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('respondent_comment', sa.Text(), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('unanswered', 'draft', 'answered', 'submitted', 'observed', 'rejected', 'approved', name='response_status', native_enum=False), nullable=False),
    sa.Column('is_not_applicable', sa.Boolean(), nullable=False),
    sa.Column('not_applicable_justification', sa.Text(), nullable=True),
    sa.Column('response_version', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_question_id'], ['assessment_questions.id'], name=op.f('fk_assessment_responses_assessment_question_id_assessment_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respondent_id'], ['users.id'], name=op.f('fk_assessment_responses_respondent_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_assessment_responses_reviewer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_responses'))
    )
    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_responses_assessment_question_id'), ['assessment_question_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_assessment_responses_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_assessment_responses_respondent_id'), ['respondent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_responses_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_responses_status'), ['status'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('business_function_id', sa.Integer(), nullable=True),
    sa.Column('security_practice_id', sa.Integer(), nullable=True),
    sa.Column('practice_stream_id', sa.Integer(), nullable=True),
    sa.Column('assessment_question_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='recommendation_priority', native_enum=False), nullable=False),
    sa.Column('effort', sa.String(length=80), nullable=True),
    sa.Column('suggested_owner', sa.String(length=180), nullable=True),
    sa.Column('time_horizon', sa.String(length=80), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'planned', 'in_progress', 'completed', 'dismissed', name='recommendation_status', native_enum=False), nullable=False),
    sa.Column('is_quick_win', sa.Boolean(), nullable=False),
    sa.Column('target_maturity_level', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_recommendations_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessment_question_id'], ['assessment_questions.id'], name=op.f('fk_recommendations_assessment_question_id_assessment_questions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_function_id'], ['business_functions.id'], name=op.f('fk_recommendations_business_function_id_business_functions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_recommendations_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practice_stream_id'], ['practice_streams.id'], name=op.f('fk_recommendations_practice_stream_id_practice_streams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['security_practice_id'], ['security_practices.id'], name=op.f('fk_recommendations_security_practice_id_security_practices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_recommendations_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_public_id'), ['public_id'], unique=True)

    op.create_table('evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_question_id', sa.Integer(), nullable=False),
    sa.Column('assessment_response_id', sa.Integer(), nullable=True),
    sa.Column('response_version', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('internal_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('reported_mime_type', sa.String(length=160), nullable=True),
    sa.Column('detected_mime_type', sa.String(length=160), nullable=True),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation_status', sa.Enum('pending', 'valid', 'rejected', 'quarantined', name='evidence_validation_status', native_enum=False), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_question_id'], ['assessment_questions.id'], name=op.f('fk_evidences_assessment_question_id_assessment_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assessment_response_id'], ['assessment_responses.id'], name=op.f('fk_evidences_assessment_response_id_assessment_responses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_evidences_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_evidences_uploaded_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidences')),
    sa.UniqueConstraint('internal_filename', name=op.f('uq_evidences_internal_filename')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_evidences_storage_key'))
    )
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidences_assessment_question_id'), ['assessment_question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidences_assessment_response_id'), ['assessment_response_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidences_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidences_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_evidences_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidences_uploaded_by_id'), ['uploaded_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidences_validation_status'), ['validation_status'], unique=False)

    op.create_table('response_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_response_id', sa.Integer(), nullable=False),
    sa.Column('response_version', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('transition_from', sa.String(length=40), nullable=True),
    sa.Column('transition_to', sa.String(length=40), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_response_id'], ['assessment_responses.id'], name=op.f('fk_response_history_assessment_response_id_assessment_responses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_response_history_changed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_response_history')),
    sa.UniqueConstraint('assessment_response_id', 'response_version', name='uq_response_history_version')
    )
    with op.batch_alter_table('response_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_response_history_assessment_response_id'), ['assessment_response_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_history_changed_by_id'), ['changed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_response_history_public_id'), ['public_id'], unique=True)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_response_id', sa.Integer(), nullable=False),
    sa.Column('response_version', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'observed', 'rejected', 'reopened', name='review_decision', native_enum=False), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_response_id'], ['assessment_responses.id'], name=op.f('fk_reviews_assessment_response_id_assessment_responses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_assessment_response_id'), ['assessment_response_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reviews_reviewer_id'), ['reviewer_id'], unique=False)

    # ### end Alembic commands ###



def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_public_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_decision'))
        batch_op.drop_index(batch_op.f('ix_reviews_assessment_response_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('response_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_response_history_public_id'))
        batch_op.drop_index(batch_op.f('ix_response_history_changed_by_id'))
        batch_op.drop_index(batch_op.f('ix_response_history_assessment_response_id'))

    op.drop_table('response_history')
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidences_validation_status'))
        batch_op.drop_index(batch_op.f('ix_evidences_uploaded_by_id'))
        batch_op.drop_index(batch_op.f('ix_evidences_sha256'))
        batch_op.drop_index(batch_op.f('ix_evidences_public_id'))
        batch_op.drop_index(batch_op.f('ix_evidences_is_active'))
        batch_op.drop_index(batch_op.f('ix_evidences_assessment_response_id'))
        batch_op.drop_index(batch_op.f('ix_evidences_assessment_question_id'))

    op.drop_table('evidences')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_public_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_priority'))
        batch_op.drop_index(batch_op.f('ix_recommendations_is_active'))
        batch_op.drop_index(batch_op.f('ix_recommendations_assessment_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('assessment_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_responses_status'))
        batch_op.drop_index(batch_op.f('ix_assessment_responses_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_responses_respondent_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_responses_public_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_responses_assessment_question_id'))

    op.drop_table('assessment_responses')
    with op.batch_alter_table('questionnaire_version_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionnaire_version_questions_questionnaire_version_id'))
        batch_op.drop_index(batch_op.f('ix_questionnaire_version_questions_question_revision_id'))
        batch_op.drop_index(batch_op.f('ix_questionnaire_version_questions_public_id'))

    op.drop_table('questionnaire_version_questions')
    with op.batch_alter_table('question_quality_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_quality_criteria_question_revision_id'))
        batch_op.drop_index(batch_op.f('ix_question_quality_criteria_public_id'))

    op.drop_table('question_quality_criteria')
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_questions_source_question_revision_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_questions_public_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_questions_external_code_snapshot'))
        batch_op.drop_index(batch_op.f('ix_assessment_questions_current_status'))
        batch_op.drop_index(batch_op.f('ix_assessment_questions_assessment_id'))

    op.drop_table('assessment_questions')
    with op.batch_alter_table('question_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_revisions_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_revisions_public_id'))
        batch_op.drop_index(batch_op.f('ix_question_revisions_content_hash'))

    op.drop_table('question_revisions')
    with op.batch_alter_table('assessment_score_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_score_items_score_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_score_items_public_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_score_items_dimension_type'))

    op.drop_table('assessment_score_items')
    with op.batch_alter_table('practice_streams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_streams_security_practice_id'))
        batch_op.drop_index(batch_op.f('ix_practice_streams_public_id'))
        batch_op.drop_index(batch_op.f('ix_practice_streams_is_active'))

    op.drop_table('practice_streams')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_public_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_public_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('assessment_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_users_public_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_users_assessment_id'))

    op.drop_table('assessment_users')
    with op.batch_alter_table('assessment_score_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_score_snapshots_public_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_score_snapshots_assessment_id'))

    op.drop_table('assessment_score_snapshots')
    with op.batch_alter_table('security_practices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_practices_public_id'))
        batch_op.drop_index(batch_op.f('ix_security_practices_is_active'))
        batch_op.drop_index(batch_op.f('ix_security_practices_business_function_id'))

    op.drop_table('security_practices')
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_memberships_public_id'))
        batch_op.drop_index(batch_op.f('ix_organization_memberships_organization_id'))

    op.drop_table('organization_memberships')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_target_date'))
        batch_op.drop_index(batch_op.f('ix_assessments_status'))
        batch_op.drop_index(batch_op.f('ix_assessments_questionnaire_version_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_public_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_organization_id'))

    op.drop_table('assessments')
    with op.batch_alter_table('answer_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_options_public_id'))
        batch_op.drop_index(batch_op.f('ix_answer_options_is_active'))
        batch_op.drop_index(batch_op.f('ix_answer_options_answer_set_id'))

    op.drop_table('answer_options')
    op.drop_table('user_roles')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_public_id'))
        batch_op.drop_index(batch_op.f('ix_questions_is_active'))
        batch_op.drop_index(batch_op.f('ix_questions_external_code'))

    op.drop_table('questions')
    with op.batch_alter_table('questionnaire_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionnaire_versions_public_id'))

    op.drop_table('questionnaire_versions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_tax_identifier'))
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_public_id'))
        batch_op.drop_index(batch_op.f('ix_organizations_is_active'))

    op.drop_table('organizations')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_public_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_active'))

    op.drop_table('notifications')
    with op.batch_alter_table('maturity_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maturity_levels_public_id'))
        batch_op.drop_index(batch_op.f('ix_maturity_levels_is_active'))

    op.drop_table('maturity_levels')
    with op.batch_alter_table('business_functions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_functions_public_id'))
        batch_op.drop_index(batch_op.f('ix_business_functions_is_active'))
        batch_op.drop_index(batch_op.f('ix_business_functions_code'))

    op.drop_table('business_functions')
    with op.batch_alter_table('application_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_settings_public_id'))
        batch_op.drop_index(batch_op.f('ix_application_settings_key'))
        batch_op.drop_index(batch_op.f('ix_application_settings_is_active'))

    op.drop_table('application_settings')
    with op.batch_alter_table('answer_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_sets_public_id'))
        batch_op.drop_index(batch_op.f('ix_answer_sets_is_active'))
        batch_op.drop_index(batch_op.f('ix_answer_sets_content_hash'))

    op.drop_table('answer_sets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_public_id'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email_normalized'))
        batch_op.drop_index('ix_users_email_active')

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_public_id'))
        batch_op.drop_index(batch_op.f('ix_roles_is_active'))
        batch_op.drop_index(batch_op.f('ix_roles_code'))

    op.drop_table('roles')
    # ### end Alembic commands ###
